### ISSUE TITLE
[Design Suggestion] Have the button on hover match the background sunset image

### ISSUE THREAD

**Issue by ryan-dalton** [Rdohrman/rdohrman.github.io#2]
On the login css, I would experiment with changing the button hover on submit to match a color similar to the sunset that is behind it - see the attached code snippet.

`.loginbox input[type="submit"]:hover
{
    cursor: pointer;
    opacity: 0.9;
    background-color: orangered;
    color: white;
}`

![image](https://user-images.githubusercontent.com/46613215/89131514-96ff0880-d4ca-11ea-8a78-e74709514691.png)

**Comment by Rdohrman** [comment]
Great idea - I just changed it. Thanks!
